In [ ]:
from IPython.display import Image
Image(filename='Questions/Day 3.jpg') 

In [1]:
# Step 1: Data Preprocessing
# Import the Libraries

import pandas as pd
import numpy as np

In [2]:
# Importing the dataset

dataset = pd.read_csv('datasets/50_Startups.csv')
print(len(dataset))
print(dataset.head())

50
   R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94


In [3]:
X = dataset.iloc[ : , :-1].values
Y = dataset.iloc[ : ,  4 ].values
print(X[:5])
print(Y[:5])

[[165349.2 136897.8 471784.1 'New York']
 [162597.7 151377.59 443898.53 'California']
 [153441.51 101145.55 407934.54 'Florida']
 [144372.41 118671.85 383199.62 'New York']
 [142107.34 91391.77 366168.42 'Florida']]
[192261.83 191792.06 191050.39 182901.99 166187.94]


In [4]:
# Encoding Categorical data

from sklearn.preprocessing import LabelEncoder, OneHotEncoder

labelencoder = LabelEncoder()
X[:,3] = labelencoder.fit_transform(X[ : , 3])
print(X[:5])

from sklearn.compose import ColumnTransformer

columnTransformer = ColumnTransformer([('encoder', OneHotEncoder(), [3])], remainder='passthrough')
X=np.array(columnTransformer.fit_transform(X),dtype=np.str)
print(X[:5])

[[165349.2 136897.8 471784.1 2]
 [162597.7 151377.59 443898.53 0]
 [153441.51 101145.55 407934.54 1]
 [144372.41 118671.85 383199.62 2]
 [142107.34 91391.77 366168.42 1]]
[['0.0' '0.0' '1.0' '165349.2' '136897.8' '471784.1']
 ['1.0' '0.0' '0.0' '162597.7' '151377.59' '443898.53']
 ['0.0' '1.0' '0.0' '153441.51' '101145.55' '407934.54']
 ['0.0' '0.0' '1.0' '144372.41' '118671.85' '383199.62']
 ['0.0' '1.0' '0.0' '142107.34' '91391.77' '366168.42']]


In [5]:
# Avoiding Dummy Variable Trap

X = X[ : , 1: ]
print(X)

[['0.0' '1.0' '165349.2' '136897.8' '471784.1']
 ['0.0' '0.0' '162597.7' '151377.59' '443898.53']
 ['1.0' '0.0' '153441.51' '101145.55' '407934.54']
 ['0.0' '1.0' '144372.41' '118671.85' '383199.62']
 ['1.0' '0.0' '142107.34' '91391.77' '366168.42']
 ['0.0' '1.0' '131876.9' '99814.71' '362861.36']
 ['0.0' '0.0' '134615.46' '147198.87' '127716.82']
 ['1.0' '0.0' '130298.13' '145530.06' '323876.68']
 ['0.0' '1.0' '120542.52' '148718.95' '311613.29']
 ['0.0' '0.0' '123334.88' '108679.17' '304981.62']
 ['1.0' '0.0' '101913.08' '110594.11' '229160.95']
 ['0.0' '0.0' '100671.96' '91790.61' '249744.55']
 ['1.0' '0.0' '93863.75' '127320.38' '249839.44']
 ['0.0' '0.0' '91992.39' '135495.07' '252664.93']
 ['1.0' '0.0' '119943.24' '156547.42' '256512.92']
 ['0.0' '1.0' '114523.61' '122616.84' '261776.23']
 ['0.0' '0.0' '78013.11' '121597.55' '264346.06']
 ['0.0' '1.0' '94657.16' '145077.58' '282574.31']
 ['1.0' '0.0' '91749.16' '114175.79' '294919.57']
 ['0.0' '1.0' '86419.7' '153514.11' '0.0']
 

In [6]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)
print(len(X_train))
print(len(Y_train))
print(len(X_test))
print(len(Y_test))

40
40
10
10


In [7]:
# Step 2: Fitting Multiple Linear Regression to the Training set

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, Y_train)
print(regressor)

LinearRegression()


C:\Users\BoyLee\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)


In [8]:
# Step 3: Predicting the Test set results

Y_pred = regressor.predict(X_test)
print(Y_pred)
print(len(Y_pred))

[103015.20159796 132582.27760815 132447.73845175  71976.09851258
 178537.48221056 116161.24230166  67851.69209676  98791.73374687
 113969.43533013 167921.06569551]
10


C:\Users\BoyLee\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: FutureWarning: Arrays of bytes/strings is being converted to decimal numbers if dtype='numeric'. This behavior is deprecated in 0.24 and will be removed in 1.1 (renaming of 0.26). Please convert your data to numeric values explicitly instead.
  return f(*args, **kwargs)
